version: "3.8"
services:
  oracle-db:
    image: container-registry.oracle.com/database/express:21.3.0-xe
    container_name: oracle-db
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PWD=root
    volumes:
      - oracle-data:/opt/oracle/oradata

volumes:
  oracle-data: