spring:
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  jackson:
    default-property-inclusion: NON_NULL
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: never

app:
  datasource:
    oracle:
      url: jdbc:oracle:thin:@localhost:1521/XEPDB1
      driver-class-name: oracle.jdbc.OracleDriver
      main:
        username: APP_MAIN
        password: APP_MAIN_123
      batch:
        username: APP_BATCH
        password: APP_BATCH_123

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

integration:
  openlibrary:
    url: https://openlibrary.org
