spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: API
    password: api123
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
  jackson:
    default-property-inclusion: NON_NULL

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

integration:
  openlibrary:
    url: https://openlibrary.org
